var ENV_CLIENT_PUBLIC_KEY;
var ENV_CLIENT_PUBLIC_KEY_HASH;
var ENV_CLIENT_PRIVATE_KEY;
var ENV_SERVER_PUBLIC_KEY;
var ENV_USER_ID;

var ENV_SERVER_ADDRESS = loadObject("SERVER_ADDR");
if (!ENV_SERVER_ADDRESS)
{
    ENV_SERVER_ADDRESS = "";
    saveObject("SERVER_ADDR", ENV_SERVER_ADDRESS);
}

var CURRENT_USER_ID = 0;


var ENV_AUTOLOAD_IMAGES = true;
var ENV_AUTOLOAD_LINK_IMAGES = false;

var ENV_ALLOW_NOTIFICATIONS = loadObject("ALLOW_NOTIFICATIONS");
if (ENV_ALLOW_NOTIFICATIONS == null)
{
    ENV_ALLOW_NOTIFICATIONS = true;
    saveObject("ALLOW_NOTIFICATIONS", ENV_ALLOW_NOTIFICATIONS);
}

var ENV_ALLOW_MSG_SOUND = loadObject("ALLOW_MSG_SOUND");
if (ENV_ALLOW_MSG_SOUND == null)
{
    ENV_ALLOW_MSG_SOUND = true;
    saveObject("ALLOW_MSG_SOUND", ENV_ALLOW_MSG_SOUND);
}
